---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'SSB'
SiteConfig:
  extensions:
    - CustomSiteConfig
Image:
  extensions:
    - ImageExtension
Member:
  extensions:
    - UserExtension
Post:
  extensions:
    - CommentableItem
FilteredListingPage_Controller:
  extensions:
    - ItemComment_Controller
OpauthAuthenticator:
  enabled_strategies:
    - GitHubStrategy
    - TwitterStrategy
  opauth_settings:
    Strategy:
      Github:
        client_id: '65712efa9de18a15fc98'
        client_secret: '0a75f7002e8993b01d4d59efc322f52b6f793e67'
      Twitter:
        key: 'zDglt0Syk4Odlk59V6cCjqsUw'
        secret: 'tmuYIpyQHggu7Ke3wgfeDRb8DyFHJGagxJAuAzsSaiCNcC9mea'
    security_salt: 'correct horse battery staple'
OpauthIdentity:
  member_mapper:
    Github:
      FirstName: ['OpauthResponseHelper', 'get_first_name']
      Surname: ['OpauthResponseHelper', 'get_last_name']
      Email: 'info.email'
    Twitter:
      FirstName: ['OpauthResponseHelper', 'get_first_name']
      Surname: ['OpauthResponseHelper', 'get_last_name']
      Locale: ['OpauthResponseHelper', 'get_twitter_locale']